### ISSUE TITLE
Slack actions with webhook messages

### ISSUE THREAD

**Issue by jamesspi** [stdlib/utils.templates#11]
Hi,

I've been using stdlib to create a slack bot, and so far I have managed to use slash commands with actions without a problem, working as expected.

However, I am having an issue with the same message being posted via webhooks. I cannot get the action to work. When I click on one of the buttons, it just stops at "Initiated actions...".

Any ideas as to what might be going on here? attachment configuration in the webhook message is identical to that in the slash command. Using postman to test.

Thanks!
James

**Comment by jamesspi** [comment]
Hi @jacoblee93,

Thanks for the prompt response!

I'm literally doing the following within postman and curl (sanitized):

`curl -X POST \
  https://hooks.slack.com/services/XXXXXXXXXXXXXXXXXXX \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
         "text": "Alert (test)",
    "attachments": [
        {
            "text": "Silly user attempted to login at 1.1.1.1",
            "fallback": "cannot acknowledge",
            "callback_id": "example",
            "attachment_type": "default",
            "actions": [
                {
                    "name": "acknowledge",
                    "text": "Acknowledge :+1:",
                    "type": "button",
                    "value": "ack",
                    "style": "primary"
                },
                {
                    "name": "example",
                    "text": "Report :exclamation:",
                    "type": "button",
                    "value": "example",
                    "style": "danger"
                }
            ]
        }
    ]
}'`

I assumed I might be using the wrong method, but I'm not entirely sure how to troubleshoot further. 

Thanks again,
James

**Comment by jacoblee93** [comment]
Could you try to make another StdLib function that just calls Slack's `postMessage` API with the parameters given? Then you can use that URL as your webhook (maybe with `:bg` at the end if you need a response right away). Something like: 
```
const slack = require('slack');

module.exports = (context, callback) => {

    slack.chat.postMessage({
      token: <your_bot_token>,
      channel: <channel>,
      text: 'blahblah',
      attachments: ['whatever attachments you want]
    }, callback);

};
```
I'm not sure what Slack is doing internally in their hook, but I imagine it's not allowing you to update the message with` updateMessage`.

As an aside, the reason we use `updateMessage` is because Slack has a restriction where you can't update messages with that `response_url` after a really short period of time (around half an hour).

**Comment by jamesspi** [comment]
Hi Jacob,

Thanks - I'll explore this option and let you know how it goes. 

James

**Comment by jamesspi** [comment]
Hey @jacoblee93 ,

This does indeed work, thanks for that!

Excuse my ignorance (not a developer), what would I need to do for this to accept certain parameters from a payload? I would need to pass certain parameters that would then populate the slack attachment.

Thanks again,
James

**Comment by jamesspi** [comment]
You're the man! Thanks again Jacob!

**Comment by jacoblee93** [comment]
Happy to help! Let me know if you have any other questions - you should also join our Slack channel (invite link under the community tab at https://stdlib.com). We're really active there.

**Comment by jamesspi** [comment]
Thanks @jacoblee93, joined the channel now :) Params request also worked!

Closing this issue.
